export const GET_CINEMA_INFO = "GET_CINEMA_INFO";
export const GET_CINEMA_SHOW_TIME = "GET_CINEMA_SHOW_TIME";
export const GET_CINEMA_DETAIL = "GET_CINEMA_DETAIL";
export const BOOKING_TICKET = "BOOKING_TICKET";
export const SELECTED_CINE = "SELECTED_CINE";
export const SHOW_TIMES_BY_CINEMA = "SHOW_TIMES_BY_CINEMA";
export const RESET_CINEMA_DETAIL = "RESET_CINEMA_DETAIL";
