export const SET_MOVIE_LIST = "SET_MOVIE_LIST";
export const SET_SHOWING_MOVIE = "SET_SHOWING_MOVIE";
export const SET_COMING_SOON_MOVIE = "SET_COMING_SOON_MOVIE";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
